### ISSUE TITLE
Remove sound effect

### ISSUE THREAD

**Issue by gergoradeczki** [kir-dev/sch-pincer#144]
Title

**Comment by nmate980829** [comment]
![image](https://user-images.githubusercontent.com/23620633/161149328-3af883c4-d111-47e9-8e7b-f69759352de4.png)
![image](https://user-images.githubusercontent.com/23620633/161149377-f8d1d2d7-8828-4ad9-9aa9-05e940708ff8.png)
![image](https://user-images.githubusercontent.com/23620633/161149422-0c95e5a8-be2b-40c4-955e-256e6ab3a294.png)

**Comment by gergoradeczki** [comment]
@nmate980829 
Thank you Kanye, very cool.

Also, could you please show me how to do this on my smart fridge?
