### ISSUE TITLE
Aktív rendelések nézet nem frissül

### ISSUE THREAD

**Issue by Omcsesz** [kir-dev/sch-pincer#155]
Sziasztok!

Az aktív rendelések nézet nem frissül egy héttel a rendelés lezárulása után sem. Ki tudnátok javítani?

**Comment by Gerviba** [comment]
Hali!

Akkor kerül lezárásara a rendelés ha a kör lezárja. Ez nem hiba, csak a körtagok nem nyomják meg a lezárás gombot. A rendelés után 2-3 héttel a rendszer amúgy lezárja magától.

Schámi
