### ISSUE TITLE
Check if time zones are okay in docker

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/sch-pincer#43]
Right now when I manually create an opening on my localhost, I cannot order at the start of ordering season, because `dto/ItemEntityDto` upon initializtaion checks `orderable` like this:
```kotlin
init { ...
  orderable = base.orderable && opening != null && opening.isInInterval(System.currentTimeMillis()) ...
```

Now `opening.isInInterval()` compares with database's times but `System.currentTimeMillis()` gets a UTC zoned time. So I can only start ordering 2 hours later (reason: GMT+2) than the real start of the ordering season.

Question is: Is it working well on the live version? Because then we won't have to hack it.

**Comment by danca** [comment]
This happens also in production.

**Comment by Gerviba** [comment]
Just fixed this issue!
Thanks for the report!
