### ISSUE TITLE
Feature: Unlist button 

### ISSUE THREAD

**Issue by melikgabi** [kir-dev/sch-pincer#61]
Egy "Rendelhető / Nem rendelhető" gomb jól jönne a termék edit és törlés mellé, gyorsabban lehetne a menüt változtatni anélkül, hogy törölni kéne tételeket. 
![Screenshot_20210706_103851](https://user-images.githubusercontent.com/73038965/124571577-339ef880-de48-11eb-8bd2-f19ffe4f8a82.jpg)

**Comment by Gerviba** [comment]
Accepted

**Comment by Gerviba** [comment]
Just finished this issue. Will be released in the 1.3.21 release batch.
